import type { Metadata } from "next";
import { notoSansLao, geistSans, geistMono } from "./fonts";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";
import AppSidebar from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSansLao.className} ${notoSansLao.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
